/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2019-04-19 07:49:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsps;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import io.nodehome.svm.common.biz.CoinListVO;
import io.nodehome.svm.common.CoinUtil;
import io.nodehome.cmm.service.GlobalProperties;

public final class launcher_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/home/fouri/work/nodehome-project/nodehome-launcher/webapps/ROOT/WEB-INF/lib/spring-webmvc-4.1.2.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1415631592000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.1.2.RELEASE.jar", Long.valueOf(1555659349000L));
    _jspx_dependants.put("jar:file:/home/fouri/work/nodehome-project/nodehome-launcher/webapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1555659349000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("io.nodehome.svm.common.CoinUtil");
    _jspx_imports_classes.add("io.nodehome.cmm.service.GlobalProperties");
    _jspx_imports_classes.add("io.nodehome.svm.common.biz.CoinListVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\">\r\n");
      out.write("\r\n");
      out.write("<title></title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/js/slider/dist/css/slider-pro.css\" media=\"screen\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/js/slider/libs/fancybox/jquery.fancybox.css\" media=\"screen\"/>\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.4.2/css/all.css\" integrity=\"sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns\" crossorigin=\"anonymous\">\r\n");
      out.write("    \r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/slider/libs/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/slider/dist/js/jquery.sliderPro.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/slider/libs/fancybox/jquery.fancybox.pack.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script> \r\n");
      out.write("<link href=\"/css/style.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/jquery-confirm.min.css\">\r\n");
      out.write("<script src=\"/js/jquery-confirm.min.js\"></script>\r\n");
      out.write("<script src=\"/js/tapp_interface.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\tvar j_curWID;\r\n");
      out.write("\tvar j_curANM;\r\n");
      out.write("  \tvar slider;\r\n");
      out.write("\tvar isLoding = false;\r\n");
      out.write("\r\n");
      out.write("\tvar pageCnt = 0;\r\n");
      out.write("\tvar maxPageNo = 0;\r\n");
      out.write("\tvar rtnServiceList;\r\n");
      out.write("\tvar imageFolder = \"\";\r\n");
      out.write("\tvar serviceIds = \"\";\t// 보유한 서비스ID 목록\r\n");
      out.write("    \r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t//$('#body_container').click(function(){\r\n");
      out.write("\t\t//});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tvar localHost;\r\n");
      out.write("\tvar j_curNetId;\r\n");
      out.write("\tvar j_isAbleTestNet;\r\n");
      out.write("\tvar j_isAbleDebugNet;\r\n");
      out.write("\t\r\n");
      out.write("\t// Function to call as soon as it is loaded from the App\r\n");
      out.write("\tfunction AWI_OnLoadFromApp(dtype) {\r\n");
      out.write("\t\t// Activate AWI_XXX method\r\n");
      out.write("\t\tAWI_ENABLE = true;\r\n");
      out.write("\t    AWI_DEVICE = dtype;\r\n");
      out.write("\t    \r\n");
      out.write("\t \t// 서비스 앱 초기화 \r\n");
      out.write("\t\tAWI_setTerminatePath('/launcher');\r\n");
      out.write("\t\t//AWI_closeServiceApp();\t\r\n");
      out.write("\t\t \r\n");
      out.write("\t\tif(!isLoding) {\t// slidePro때문에 AWI_OnLoadFromApp()가 두번이상 호출되는 문제\r\n");
      out.write("\t\t    j_curWID = AWI_getAccountConfig(\"CUR_WID\");\r\n");
      out.write("\t\t\tj_curANM = AWI_getAccountConfig(\"ACCOUNT_NM\");\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t j_isAbleTestNet = AWI_isAbleTestNet();\r\n");
      out.write("\t\t\t j_isAbleDebugNet = AWI_isAbleDebugNet();\r\n");
      out.write("\r\n");
      out.write("\t\t\t if(j_isAbleTestNet==\"OK\" || j_isAbleDebugNet==\"OK\") {\r\n");
      out.write("\t\t\t\t $('#netIdBtn').show();\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t\t if(j_isAbleTestNet==\"OK\") {\r\n");
      out.write("\t             var option = $(\"<option value='TestNet'>TestNet</option>\");\r\n");
      out.write("\t             $('#netId').append(option); \r\n");
      out.write("\t\t\t } \r\n");
      out.write("\t\t\t if(j_isAbleDebugNet==\"OK\") {\r\n");
      out.write("\t             var option = $(\"<option value='DebugNet'>DebugNet</option>\");\r\n");
      out.write("\t             $('#netId').append(option); \r\n");
      out.write("\t\t\t }\r\n");
      out.write("\r\n");
      out.write("\t\t\t j_curNetId = (AWI_getNetID())['value'];\r\n");
      out.write("\t\t\t $('#netId').val(j_curNetId);\r\n");
      out.write("\t\t\t if(j_curNetId!=\"MainNet\") $('#goHostBtn').show();\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\tif(j_curWID==\"\") {\r\n");
      out.write("\t\t\t\t location.href=\"/svm/wallet/myWalletList\";\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t //var myBalance = getBalance(j_curWID);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar chk = AWI_isCheckedPassword();\r\n");
      out.write("\t\t\tif(chk!=\"OK\") location.href=\"/user/login\";\r\n");
      out.write("\r\n");
      out.write("\t\t\tlocalHost = AWI_getLocalHttpHost();\r\n");
      out.write("\t\t\trtnServiceList = AWI_getServiceList();\r\n");
      out.write("\t\t\tloadServices();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tFn_initDisplay();\r\n");
      out.write("\t\t\tdrawPageIcon();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 페이지 슬라이드 출력후에 실행 초기화\r\n");
      out.write("\tfunction Fn_initDisplay() {\r\n");
      out.write("\t\t$( '#body_container' ).sliderPro({\r\n");
      out.write("\t\t\tautoHeight: true,\r\n");
      out.write("\t\t\tfade: true,\r\n");
      out.write("\t\t\tupdateHash: true,\r\n");
      out.write("\t\t\tloop: false,\r\n");
      out.write("\t\t\tautoplay: false,\r\n");
      out.write("\t\t\tbuttons: false,\r\n");
      out.write("\t\t\theightMinus: (60+40+20),\r\n");
      out.write("\t\t\tforceSize:'fullWindow',\r\n");
      out.write("\t\t\tkeyboard:false,\r\n");
      out.write("\t\t\tautoScaleLayers: false,\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('.sp-slide .row').css(\"min-height\",$( window ).height()-(60+40+20));\r\n");
      out.write("\r\n");
      out.write("\t\t$( '#body_container .sp-lightbox' ).on( 'click', function( event ) {\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\tif ( $( '#body_container' ).hasClass( 'sp-swiping' ) === false ) {\r\n");
      out.write("\t\t\t\t$.fancybox.open( this );\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tslider = $( '#body_container' ).data( 'sliderPro' );\r\n");
      out.write("\t\t$( '#body_container' ).on( 'gotoSlide', function( event ) {\r\n");
      out.write("\t\t\tdrawPageIcon();\r\n");
      out.write("\t\t\t$('#pageNo').val(slider.getSelectedSlide()+1);\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tif(maxPageNo>2) {slider.settings.loop = true;}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tisLoding = true;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction drawPageIcon() {\r\n");
      out.write("\t\t//$('#page-no').html(slider.getSelectedSlide()+1);\t// 페이지 번호\r\n");
      out.write("\t\t// draw page icon\r\n");
      out.write("\t\t$('#page-no').html(\"\");\r\n");
      out.write("\t\tfor(var ii=0; ii<pageCnt; ii++) {\r\n");
      out.write("\t\t\tif(slider.getSelectedSlide() == ii)\r\n");
      out.write("\t\t\t\t$('#page-no').append(\"<span style='color:#fff;padding-left:10px;padding-right:10px;'>\"+(ii+1)+\"</span>\");\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\t$('#page-no').append(\"<span style='color:#B5CB8E;padding-left:10px;padding-right:10px;'>\"+(ii+1)+\"</span>\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction loadServices() {\r\n");
      out.write("\t\tvar serviceList = [[]];\r\n");
      out.write("\t\tif(rtnServiceList['result']==\"OK\") {\r\n");
      out.write("\t\t\tvar objServices = rtnServiceList['list'];\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//alert(JSON.stringify(rtnServiceList));\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\timageFolder = rtnServiceList['imageFolder'];\r\n");
      out.write("\t\t\tfor(var i=0; i<objServices.length; i++) {\r\n");
      out.write("\t\t\t\tvar obj = objServices[i];\r\n");
      out.write("\t\t\t\tvar pageNum = obj['pageNum']; if(pageNum<1) pageNum=1;\r\n");
      out.write("\t\t\t\tif(pageNum > maxPageNo) maxPageNo = pageNum;\r\n");
      out.write("\r\n");
      out.write("\t\t        var tempObj = serviceList[(pageNum-1)];\r\n");
      out.write("\t\t        if(serviceList.length < pageNum) {\t// serviceList 배열 초기화 체크\r\n");
      out.write("\t\t        \tfor(var a=serviceList.length; a<pageNum; a++) {\r\n");
      out.write("\t\t    \t        var tempObj2 = serviceList[a];\r\n");
      out.write("\t\t    \t        if(tempObj2===undefined) {\r\n");
      out.write("\t\t        \t\t\tserviceList.push([]);\r\n");
      out.write("\t\t    \t        }\r\n");
      out.write("\t\t        \t}\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t        var tempObj = serviceList[(pageNum-1)];\r\n");
      out.write("\t\t        tempObj.push(\"{\\\"serviceId\\\":\\\"\"+obj[\"serviceId\"]+\"\\\",\\\"serviceName\\\":\\\"\"+obj[\"serviceName\"]+\"\\\",\\\"defaultCheck\\\":\\\"false\\\"}\");\r\n");
      out.write("\t\t        serviceList[(pageNum-1)] = tempObj;\t\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdisplayServices(serviceList);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction displayServices(serviceList) {\r\n");
      out.write("\t\t$('.sp-slides').html(\"\");\r\n");
      out.write("\t\tvar sHtml = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\tpageCnt = 0;\r\n");
      out.write("\t\tserviceIds = \"\";\r\n");
      out.write("\t\tfor(var i=0; i<serviceList.length; i++) {\r\n");
      out.write("\t\t\tsHtml += '<div class=\"sp-slide\">';\r\n");
      out.write("\t\t\tsHtml += '\t<div class=\"row\" style=\"margin:0;\">';\r\n");
      out.write("\t\t\tif(serviceList[i].length>0) {\r\n");
      out.write("\t\t\t\tfor(var i2=0; i2<serviceList[i].length; i2++) {\r\n");
      out.write("\t\t\t\t\tvar tempObj = JSON.parse(serviceList[i][i2]);\r\n");
      out.write("\t\t\t\t\tsHtml += '\t\t<div class=\"col-xs-6 col-sm-6\" style=\"text-align:center;padding:5px;\" id=\"sp-col-'+i+'-'+i2+'\">';\r\n");
      out.write("\t\t\t\t\tsHtml += '\t\t\t<img src=\"'+localHost+'/'+imageFolder+'/'+tempObj['serviceId']+'/icon.png\" width=80 height=80 style=\"border-radius:25px;\"  onclick=\"javascript:AWI_openServiceApp(\\''+tempObj['serviceId']+'\\');\" /><br/>';\r\n");
      out.write("\t\t\t\t\tsHtml += '\t\t\t<div style=\"height:50px;\">';\r\n");
      out.write("\t\t\t\t\tif(tempObj['defaultCheck']==\"true\") { \r\n");
      out.write("\t\t\t\t\t\tsHtml += '\t\t\t<input type=\"checkbox\" class=\"serviceChkBox\" name=\"serviceValue\" value=\"'+(i+1)+'|'+(i2+1)+'|'+tempObj['serviceId']+'|'+tempObj['serviceName']+'\" checked style=\"display:none;\" />';\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tsHtml += '\t\t\t<input type=\"checkbox\" class=\"serviceChkBox\" name=\"serviceValue\" value=\"'+(i+1)+'|'+(i2+1)+'|'+tempObj['serviceId']+'|'+tempObj['serviceName']+'\" style=\"display:none;\" />';\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tsHtml += '\t\t\t'+tempObj['serviceName']+'</div>';\r\n");
      out.write("\t\t\t\t\tsHtml += '\t\t</div>';\r\n");
      out.write("\t\t\t\t\tserviceIds += tempObj['serviceId']+\",\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tsHtml += '\t</div>';\r\n");
      out.write("\t\t\tsHtml += '</div>';\r\n");
      out.write("\t\t\tpageCnt++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(serviceIds.length > 0) serviceIds = serviceIds.substring(0,serviceIds.length-1);\r\n");
      out.write("\t\t$('.sp-slides').append(sHtml);\r\n");
      out.write("\t\t//$('#tot-page-no').html(pageCnt);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("    function readURL(input) {\r\n");
      out.write("        if (input.files && input.files[0]) {\r\n");
      out.write("            var reader = new FileReader();\r\n");
      out.write("            reader.onload = function(e) {\r\n");
      out.write("                $('#foo').attr('src', e.target.result);\r\n");
      out.write("            }\r\n");
      out.write("            reader.readAsDataURL(input.files[0]);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tvar onMenu = false;\r\n");
      out.write("\tfunction onMainMenu() {\r\n");
      out.write("\t\tonMenu = !onMenu;\r\n");
      out.write("\t\tchangeMainMenu(onMenu);\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeMainMenu(chk) {\r\n");
      out.write("\t\tonMenu = chk;\r\n");
      out.write("\t\tif (chk) {\r\n");
      out.write("\t\t\t$('#menu-box').animate({ top : \"50px\" }, 300);\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$('#netIdDiv').hide();\r\n");
      out.write("\t\t\t$('#menu-box').animate({ top : \"-500px\" }, 300);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction changemngMenuPop(chk) {\r\n");
      out.write("\t\tif (chk) {\r\n");
      out.write("\t\t\t$('#mngMenuPop').show(300);\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$('#mngMenuPop').hide(300);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tvar defaultBottomGap = 40;\r\n");
      out.write("\tvar openBottomGap = 250;\r\n");
      out.write("\t\r\n");
      out.write("\tfunction loadManagerBox() {\r\n");
      out.write("\t\tonMenu = false;\r\n");
      out.write("\t\tchangeMainMenu(false);\r\n");
      out.write("\r\n");
      out.write("\t\tchangemngMenuPop(true);\r\n");
      out.write("\t\tchangeBottomGapSize(openBottomGap);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 하단 여백 조정\r\n");
      out.write("\tfunction changeBottomGapSize(height) {\r\n");
      out.write("\t\t$('#bottomGap').css(\"height\",height+\"px\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction closePop(pid) {\r\n");
      out.write("\t\t$('#'+pid).hide(300);\r\n");
      out.write("\t\tchangeBottomGapSize(defaultBottomGap);\r\n");
      out.write("\t\t$('.serviceChkBox').hide();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction iconSelMove() {\r\n");
      out.write("\t\t$('#btn-list1').hide();\r\n");
      out.write("\t\t$('#btn-list2').show();\r\n");
      out.write("\t\t$('.serviceChkBox').show();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction iconSelDel() {\r\n");
      out.write("\t\t$('#btn-list1').hide();\r\n");
      out.write("\t\t$('#btn-list3').show();\r\n");
      out.write("\t\t$('.serviceChkBox').show();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 선택 아이콘 삭제\r\n");
      out.write("\tfunction iconSelDelProc() {\r\n");
      out.write("\t\tvar serviceList = [[]];\r\n");
      out.write("\t\tvar nowSelectedPageNo = slider.getSelectedSlide()+1;\r\n");
      out.write("\t\t$('input:checkbox[name=\"serviceValue\"]').each(function() {\r\n");
      out.write("\t\t\tvar val = (this.value).split(\"|\");\r\n");
      out.write("\t\t\tvar pageNum = parseInt(val[0]);\r\n");
      out.write("\t\t\tvar pageSeq = parseInt(val[1]);\r\n");
      out.write("\t\t\tvar sId = val[2];\r\n");
      out.write("\t\t\tvar sNm = val[3];\r\n");
      out.write("\r\n");
      out.write("\t        if(serviceList.length < pageNum) {\t// serviceList 배열 초기화 체크\r\n");
      out.write("\t        \tfor(var a=serviceList.length; a<pageNum; a++) {\r\n");
      out.write("\t    \t        var tempObj2 = serviceList[a];\r\n");
      out.write("\t    \t        if(tempObj2===undefined) {\r\n");
      out.write("\t        \t\t\tserviceList.push([]);\r\n");
      out.write("\t    \t        }\r\n");
      out.write("\t        \t}\r\n");
      out.write("\t        }\r\n");
      out.write("\t\t\tif(this.checked && nowSelectedPageNo == pageNum) {\r\n");
      out.write("\t\t\t\t;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t        var tempObj = serviceList[(pageNum-1)];\r\n");
      out.write("\t\t        tempObj.push(\"{\\\"serviceId\\\":\\\"\"+sId+\"\\\",\\\"serviceName\\\":\\\"\"+sNm+\"\\\",\\\"defaultCheck\\\":\\\"false\\\"}\");\r\n");
      out.write("\t\t        serviceList[(pageNum-1)] = tempObj;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tdisplayServices(serviceList);\r\n");
      out.write("\t\tFn_initDisplay();\r\n");
      out.write("\t\t$('.serviceChkBox').show();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 터미널에 적용\r\n");
      out.write("\tfunction iconSelApply() {\r\n");
      out.write("\t\tvar tempStr=\"\";\r\n");
      out.write("\t\tvar index=0;\r\n");
      out.write("\t\t$('input:checkbox[name=\"serviceValue\"]').each(function() {\r\n");
      out.write("\t\t\tvar val = (this.value).split(\"|\");\r\n");
      out.write("\t\t\tvar pageNum = parseInt(val[0]);\r\n");
      out.write("\t\t\tvar pageSeq = parseInt(val[1]);\r\n");
      out.write("\t\t\tvar sId = val[2];\r\n");
      out.write("\t\t\tvar sNm = val[3];\r\n");
      out.write("\r\n");
      out.write("\t\t\ttempStr += \"{\\\"pageNum\\\":\"+pageNum+\",\\\"seqNum\\\":\"+pageSeq+\",\\\"serviceId\\\":\\\"\"+sId+\"\\\",\\\"serviceName\\\":\\\"\"+sNm+\"\\\",\\\"active\\\":\";\r\n");
      out.write("\t\t\tif(index==0) tempStr += \"\\\"Y\\\"\";\r\n");
      out.write("\t\t\telse tempStr += \"\\\"N\\\"\";\r\n");
      out.write("\t\t\ttempStr += \"},\";\r\n");
      out.write("\t\t\tindex++;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tif(tempStr.length>0) tempStr = tempStr.substring(0,tempStr.length-1);\r\n");
      out.write("\t\t// Save to service terminal \r\n");
      out.write("\t\tjoReturn = AWI_setServiceList(tempStr,'launcher');\r\n");
      out.write("\r\n");
      out.write("\t\tif(joReturn['result']==\"OK\") {\r\n");
      out.write("\t\t\t$('.serviceChkBox').hide();\r\n");
      out.write("\t\t\t$('#btn-list2').hide();\r\n");
      out.write("\t\t\t$('#btn-list3').hide();\r\n");
      out.write("\t\t\t$('#btn-list1').show();\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$.alert(\"저장에 실패했습니다.\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdrawPageIcon();\t// 페이지 아이콘 다시 그리기\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction cancelSelApply() {\r\n");
      out.write("\t\t$('.serviceChkBox').hide();\r\n");
      out.write("\t\t$('#btn-list2').hide();\r\n");
      out.write("\t\t$('#btn-list3').hide();\r\n");
      out.write("\t\t$('#btn-list1').show();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction changeOrder(ord) {\r\n");
      out.write("\t\tvar itemList = [];\r\n");
      out.write("\t\tvar nowSelectedPageNo = slider.getSelectedSlide()+1;\r\n");
      out.write("\t\tvar curPageServiceCnt = 0;\r\n");
      out.write("\t\t$('input:checkbox[name=\"serviceValue\"]').each(function() {\r\n");
      out.write("\t\t\titemList.push(this.value+\"|\"+this.checked);\r\n");
      out.write("\t\t\tvar val = (this.value).split(\"|\");\r\n");
      out.write("\t\t\tvar pageNum = parseInt(val[0]);\r\n");
      out.write("\t\t\tif(pageNum == nowSelectedPageNo) {\r\n");
      out.write("\t\t\t\tcurPageServiceCnt++;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tif(ord==\"L\") {\r\n");
      out.write("\t\t\tvar pageIndex = 0;\r\n");
      out.write("\t\t\tfor(var i=0; i<itemList.length; i++) {\r\n");
      out.write("\t\t\t\tvar tmp = itemList[i];\r\n");
      out.write("\t\t\t\tvar val = (tmp).split(\"|\");\r\n");
      out.write("\t\t\t\tvar pageNum = parseInt(val[0]);\r\n");
      out.write("\t\t\t\tif(nowSelectedPageNo == pageNum) {\r\n");
      out.write("\t\t\t\t\tif(pageIndex>0 && val[4]==\"true\") {\r\n");
      out.write("\t\t\t\t\t\titemList.splice(i, 1);\r\n");
      out.write("\t\t\t\t\t\titemList.splice(i-1, 0, tmp);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tpageIndex++;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tvar pageIndex = (curPageServiceCnt-1);\r\n");
      out.write("\t\t\tfor(var i=(itemList.length-1); i>=0; i--) {\r\n");
      out.write("\t\t\t\tvar tmp = itemList[i];\r\n");
      out.write("\t\t\t\tvar val = (tmp).split(\"|\");\r\n");
      out.write("\t\t\t\tvar pageNum = parseInt(val[0]);\r\n");
      out.write("\t\t\t\tif(nowSelectedPageNo == pageNum) {\r\n");
      out.write("\t\t\t\t\tif(pageIndex<(curPageServiceCnt-1) && val[4]==\"true\") {\r\n");
      out.write("\t\t\t\t\t\titemList.splice(i, 1);\r\n");
      out.write("\t\t\t\t\t\titemList.splice(i+1, 0, tmp);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tpageIndex--;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar serviceList = [[]];\r\n");
      out.write("\t\tfor(var i=0; i<itemList.length; i++) {\r\n");
      out.write("\t\t\tvar val = (itemList[i]).split(\"|\");\r\n");
      out.write("\t\t\tvar pageNum = parseInt(val[0]);\r\n");
      out.write("\t\t\tvar pageSeq = parseInt(val[1]);\r\n");
      out.write("\t\t\tvar sId = val[2];\r\n");
      out.write("\t\t\tvar sNm = val[3];\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t        if(serviceList.length < pageNum) {\t// serviceList 배열 초기화 체크\r\n");
      out.write("\t        \tfor(var a=serviceList.length; a<pageNum; a++) {\r\n");
      out.write("\t    \t        var tempObj2 = serviceList[a];\r\n");
      out.write("\t    \t        if(tempObj2===undefined) {\r\n");
      out.write("\t        \t\t\tserviceList.push([]);\r\n");
      out.write("\t    \t        }\r\n");
      out.write("\t        \t}\r\n");
      out.write("\t        }\r\n");
      out.write("\t        var tempObj = serviceList[(pageNum-1)];\r\n");
      out.write("\t        tempObj.push(\"{\\\"serviceId\\\":\\\"\"+sId+\"\\\",\\\"serviceName\\\":\\\"\"+sNm+\"\\\",\\\"defaultCheck\\\":\\\"\"+val[4]+\"\\\"}\");\r\n");
      out.write("\t        serviceList[(pageNum-1)] = tempObj;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdisplayServices(serviceList);\r\n");
      out.write("\t\tFn_initDisplay();\r\n");
      out.write("\t\t$('.serviceChkBox').show();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction changePage() {\r\n");
      out.write("\t\tvar isChkItem = false;\r\n");
      out.write("\t\tvar itemList = [];\r\n");
      out.write("\t\tvar upPageNo = $('#pageNo').val();\r\n");
      out.write("\t\tif(upPageNo==\"\") {return;}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('input:checkbox[name=\"serviceValue\"]').each(function() {\r\n");
      out.write("\t\t\tif(this.checked) {\r\n");
      out.write("\t\t\t\tvar val = (this.value).split(\"|\");\r\n");
      out.write("\t\t\t\titemList.push(upPageNo+\"|999|\"+val[2]+\"|\"+val[3]+\"|false\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\titemList.push(this.value+\"|\"+this.checked);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar serviceList = [[]];\r\n");
      out.write("\t\tfor(var i=0; i<itemList.length; i++) {\r\n");
      out.write("\t\t\tvar val = (itemList[i]).split(\"|\");\r\n");
      out.write("\t\t\tvar pageNum = parseInt(val[0]);\r\n");
      out.write("\t\t\tvar pageSeq = parseInt(val[1]);\r\n");
      out.write("\t\t\tvar sId = val[2];\r\n");
      out.write("\t\t\tvar sNm = val[3];\r\n");
      out.write("\r\n");
      out.write("\t        if(serviceList.length < pageNum) {\t// serviceList 배열 초기화 체크\r\n");
      out.write("\t        \tfor(var a=serviceList.length; a<pageNum; a++) {\r\n");
      out.write("\t    \t        var tempObj2 = serviceList[a];\r\n");
      out.write("\t    \t        if(tempObj2===undefined) {\r\n");
      out.write("\t        \t\t\tserviceList.push([]);\r\n");
      out.write("\t    \t        }\r\n");
      out.write("\t        \t}\r\n");
      out.write("\t        }\r\n");
      out.write("\t        var tempObj = serviceList[(pageNum-1)];\r\n");
      out.write("\t        tempObj.push(\"{\\\"serviceId\\\":\\\"\"+sId+\"\\\",\\\"serviceName\\\":\\\"\"+sNm+\"\\\",\\\"defaultCheck\\\":\\\"false\\\"}\");\r\n");
      out.write("\t        serviceList[(pageNum-1)] = tempObj;\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdisplayServices(serviceList);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(pageCnt < (slider.getSelectedSlide()+1)) slider.gotoSlide(pageCnt-1);\r\n");
      out.write("\t\tFn_initDisplay();\r\n");
      out.write("\t\t$('.serviceChkBox').show();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction Fn_goServiceList() {\r\n");
      out.write("\t\tlocation.href=\"/svm/common/serviceSelection?serviceIds=\"+serviceIds;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction Fn_addNewServiceForm() {\r\n");
      out.write("\t\tlocation.href=\"/svm/service/addServiceForm\";\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction Fn_faucet() {\r\n");
      out.write("\t\tlocation.href=\"/faucet.jsp\";\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction Fn_actionWalletPage() {\r\n");
      out.write("\t\tlocation.href=\"/index\";\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body leftmargin=0 topmargin=0>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\tfunction Fn_openNetOption() {\r\n");
      out.write("\t\t$('#netIdDiv').show();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction Fn_redirectNetID() {\r\n");
      out.write("\t\tAWI_setNetID($('#netId').val());\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction Fn_openLocation() {\r\n");
      out.write("\t\tchangeMainMenu(false);\r\n");
      out.write("\t\t$('#locationDiv').show();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction Fn_actionLocation() {\r\n");
      out.write("\t\tif($('#locationUrl').val()!=\"\") {\r\n");
      out.write("\t\t\tAWI_openAppByHost($('#locationUrl').val());\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction calcPageNo(g) {\r\n");
      out.write("\t\tvar pn = parseInt($('#pageNo').val());\r\n");
      out.write("\t\tif(g=='+') {\r\n");
      out.write("\t\t\t$('#pageNo').val(pn+1);\r\n");
      out.write("\t\t} else if(g=='-' && pn>0){\r\n");
      out.write("\t\t\t$('#pageNo').val(pn-1);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"menu-box\" style=\"position:absolute;right:0px;top:-500px;width:100%;background-color:#424242;padding:10px;color:#000;z-index:800;\">\r\n");
      out.write("\t\t<li id=\"goHostBtn\" style=\"display:none;\" onclick=\"javascript:Fn_openLocation();\"><i class=\"fas fa-location-arrow\"></i> 호스트 가기</li>\r\n");
      out.write("\t\t<li onclick=\"javascript:loadManagerBox();\"><i class=\"fas fa-user-cog\"></i> 바탕화면 관리</li>\r\n");
      out.write("\t\t<li onclick=\"javascript:Fn_faucet();\"><i class=\"fas fa-coins\"></i> 무료 충전</li>\r\n");
      out.write("\t\t<li onclick=\"javascript:Fn_goServiceList();\"><i class=\"fas fa-search-plus\"></i> 서비스 검색</li>\r\n");
      out.write("\t\t<li onclick=\"javascript:Fn_openNetOption();\"><i class=\"fas fa-network-wired\"></i> 접속 네트워크</li>\r\n");
      out.write("\t\t<div id=\"netIdDiv\" style=\"display:none;\"> \r\n");
      out.write("\t\t\t<select name=\"netId\" id=\"netId\" class=\"form-control\" onchange=\"Fn_redirectNetID()\">\r\n");
      out.write("\t\t\t</select>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<li onclick=\"javascript:AWI_showSettingView();\"><i class=\"fas fa-cog\"></i> 설정</li>\r\n");
      out.write("\t\t<li onclick=\"javascript:Fn_addNewServiceForm();\"><i class=\"fas fa-cog\"></i> 새서비스추가</li>\r\n");
      out.write("\t\t<li onclick=\"javascript:Fn_actionWalletPage();\"><i class=\"fas fa-cog\"></i> 지갑 서비스</li>\r\n");
      out.write("\t\t<li onclick=\"javascript:AWI_logout();\"><i class=\"fas fa-sign-out-alt\"></i> 로그아웃</li> \r\n");
      out.write("\t\t<li onclick=\"javascript:changeMainMenu(false);\"><i class=\"fas fa-times\" style=\"padding-left:9px;\"></i> 메뉴 닫기</li> \r\n");
      out.write("\t</div> \r\n");
      out.write("\t<div id=\"locationDiv\" style=\"display:none;border:1px solid #ccc;\" class=\"pop-center-260-150\">\r\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-12\" style=\"height:40px;line-height:40px;margin-top:30px;\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"locationUrl\" id=\"locationUrl\" value=\"\" placeholder=\"http://www.sample.com\" class=\"form-control\" />\t\r\n");
      out.write("\t\t</div> \r\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-12\" style=\"height:60px;padding-top:15px;text-align:left;color:#127519;vertical-align: middle;line-height:60px;\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-primary col-xs-12\" onclick=\"Fn_actionLocation();\">이동</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"position:absolute;right:5px;top:-1px;font-size:20pt;font-weight:bold;\"><i class=\"fas fa-window-close\" onclick=\"$('#locationDiv').hide();\" style=\"border-radius:0;\"></i></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div style=\"width:100%;height:50px;\"></div><!-- 상단 header여백 -->\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"top_header\" style=\"position:absolute;right:0px;top:0;width:100%;height:60px;margin:0;background-color:#fff;z-index:900;border-bottom:1px solid #D0D0D0;\">\r\n");
      out.write("\t\t<div class=\"row\" style=\"margin:0;\">\r\n");
      out.write("\t\t\t<div class=\"col-xs-7 col-sm-7\" style=\"height:40px;\">\r\n");
      out.write("\t\t\t\t<a href=\"/launcher\"><img src=\"/images/nodehome.png\" width=\"138\" height=\"40\" style=\"margin-top:10px;margin-left:5px;\" /></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-xs-5 col-sm-5\" style=\"height:60px;text-align:right;\">\r\n");
      out.write("\t            <div style=\"margin-top:15px;margin-right:7px;font-size:14pt;\">\r\n");
      out.write("\t                <i class=\"fas fa-ellipsis-v\" onclick=\"onMainMenu();\" style=\"color:#414041;\"></i>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t \r\n");
      out.write("\t<div id=\"body_container\" style=\"padding-top:20px;background-image: linear-gradient(-40deg, #F6F8EC, #FFF);\"><!-- background: url(/images/bg3.png); -->\r\n");
      out.write("\t\t<div class=\"sp-slides\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- DAPP 관리 메뉴 -->\r\n");
      out.write("\t<div style=\"display:none;position:fixed;bottom:40px;left:0;border-top:1px solid #cccccc;height:160px;width:100%;vertical-align:middle;background-color:#fff;z-index:700;\" id=\"mngMenuPop\">\r\n");
      out.write("\t\t<div style=\"width:100%;height:160px;vertical-align:middle;padding:50px 10px 10px 10px;\" id=\"btn-list1\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn launcher-btn col-xs-12\" onclick=\"iconSelMove();\">아이콘 선택 이동</button>\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn launcher-btn col-xs-12\" onclick=\"iconSelDel();\">아이콘 선택 삭제</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"display:none;width:100%;height:160px;vertical-align:middle;padding:20px 10px 10px 10px;\" id=\"btn-list2\">\r\n");
      out.write("\t\t\t<div class=\"col-xs-7\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn launcher-btn3\" onclick=\"calcPageNo('-');\" style=\"margin-left:4px;\"><i class=\"fas fa-minus-circle\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"number\" id=\"pageNo\" class=\"form-control\" value=\"1\" style=\"margin-right:4px;width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn launcher-btn3\" onclick=\"calcPageNo('+');\" style=\"margin-left:4px;\"><i class=\"fas fa-plus-circle\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-xs-4\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn launcher-btn3\" onclick=\"changePage();\" style=\"margin-left:4px;\">페이지로 이동</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-xs-6\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn launcher-btn col-xs-12\" onclick=\"changeOrder('L');\">순서 앞으로</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-xs-6\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn launcher-btn col-xs-12\" onclick=\"changeOrder('R');\">순서 뒤로</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-xs-6\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn launcher-btn2 col-xs-12\" onclick=\"iconSelApply();\">적용</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-xs-6\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn launcher-btn2 col-xs-12\" onclick=\"cancelSelApply();\">취소</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"display:none;width:100%;height:160px;vertical-align:middle;padding:50px 10px 10px 10px;\" id=\"btn-list3\">\r\n");
      out.write("\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn launcher-btn col-xs-12\" onclick=\"iconSelDelProc();\">삭제</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-xs-6\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn launcher-btn2 col-xs-12\" onclick=\"iconSelApply();\">적용</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-xs-6\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn launcher-btn2 col-xs-12\" onclick=\"cancelSelApply();\">취소</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"position:absolute;right:5px;top:-30px;font-size:20pt;font-weight:bold;\"><i class=\"fas fa-window-close\" onclick=\"closePop('mngMenuPop');\"></i></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"bottomGap\" style=\"width:100%;height:40px;\"></div><!-- 하단 여백 -->\r\n");
      out.write("\t<div id=\"bottom\" style=\"position: fixed;left:0px;bottom:0;width:100%;height:40px;margin:0;z-index:900;\">\r\n");
      out.write("\t\t<div class=\"row\" style=\"margin:0;background-color:#1B5E20;\"><!-- background-image: linear-gradient(-40deg, #6F8732, #6F8732, #6F8732, #30440C); -->\r\n");
      out.write("\t\t\t<div style=\"height:40px;line-height:40px;vertical-align: middle;text-align:center;color:#000;font-size:13pt;\" id=\"page-no\">\r\n");
      out.write("\t\t\t\t<!-- <span id=\"page-no\" style=\"font-weight:bold;\">1</span> / <span id=\"tot-page-no\" style=\"color:blue;\"></span> -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
