version: '2'

networks:
  nodehome-net:
    external:
      name: nodehome-net

services:
  sns-dev.nodehome.io:
    container_name: sns-dev.nodehome.io
    image: nodehome/sns-dev:0.1
    working_dir: /home/nodehome
    command : /usr/local/bin/service-run.sh
    volumes:
    - ./config/tomcat/conf/server.xml:/opt/tomcat/conf/server.xml
    - ./config/tomcat/logs/:/opt/tomcat/logs/
    - ./config/hosts/:/home/nodehome/NodeHome-Platform-SNS/WEB-INF/hosts/
    - ./config/props/:/home/nodehome/NodeHome-Platform-SNS/WEB-INF/classes/resources/props/
    ports:
      - "SEED_PORT:8080"
    networks:
      - nodehome-net
